#!/bin/sh
set -e
export OMPI_MCA_btl_vader_single_copy_mechanism=none

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------
# Clean case before running
cleanCase0
rm -rf postProcessing
rm -rf debugElmerToFoamBC
rm -rf logs
touch case.foam

python3 createBCfiles.py
python3 createLorentzForce.py

# Create mesh from blockMesh
# python3 nemoblock-setup.py
runApplication blockMesh

# rotateMesh to match the coordinate system from Elmer
runApplication rotateMesh "(0 0 1)" "(0 1 0)"

restore0Dir
runApplication checkMesh
runApplication changeDictionary
runApplication elmerToFoamBC
# runApplication decomposePar
runApplication $(getApplication)
# # runParallel $(getApplication)
# # runApplication reconstructPar -newTimes

# paraFoam -touch
# runApplication foamLog log.$(getApplication)
# python3 plotResiduals.py

#------------------------------------------------------------------------------
