#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

wclean fvPatchFields/shearStressMarangoni

wclean elmerFoamCoupling/solvers/buoyantBoussinesqSimpleFoam

wclean elmerFoamCoupling/solvers/buoyantBoussinesqPimpleFoam

wclean elmerFoamCoupling/utilities/azimuthalAverage

wclean elmerFoamCoupling/utilities/elmerToFoamBC/elmerToFoamBC

wmake fvPatchFields/shearStressMarangoni

wmake elmerFoamCoupling/solvers/buoyantBoussinesqSimpleFoam

wmake elmerFoamCoupling/solvers/buoyantBoussinesqPimpleFoam

wmake elmerFoamCoupling/utilities/azimuthalAverage

wmake elmerFoamCoupling/utilities/elmerToFoamBC/elmerToFoamBC
